site_name: App CLI
site_url: https://myapp.com/
nav:
  - Home: index.md
  - Usage:
    - CLI: cli.md
  - Advanced:
    - Build: build.md
    - Documentation: docs.md

markdown_extensions:
    - mkdocs-click
theme: readthedocs
